### ISSUE TITLE
DS_StereoMate in data dictionary but not in UML

### ISSUE THREAD

**Issue by isotc211** [ISO-TC211/StandardsTracker#362] opened 2021-03-17 01:42 UTC
<b>Justification:</b> Missing DS_StereoMate Class from UML. OR DS_SterioMate in data dictionary without being in UML
                                     <b>Proposal:</b> Either:
Add to UML
OR
Remove from data dictionary

**Comment by PeterParslow** [comment] 2021-05-18 10:33
Duplicate of https://github.com/ISO-TC211/StandardsTracker/issues/363

**Closed** 2021-05-18 10:33 UTC
Labels: 19115-1, isotc211, technical
